name: Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  gitleaks-scan:
    uses: ./.github/workflows/gitleaks-scan.yaml

  test:
    needs: gitleaks-scan
    uses: ./.github/workflows/test.yaml

  build-release:
    needs: test
    uses: ./.github/workflows/build-release.yaml

  publish:
    needs: build-release
    uses: ./.github/workflows/publish.yaml
