name: Main

on:
  push:
    branches:
      - main

jobs:
  gitleaks-scan:
    uses: ./.github/workflows/gitleaks-scan.yaml

  test:
    needs: gitleaks-scan
    uses: ./.github/workflows/test.yaml
    with:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  build-release:
    needs: test
    uses: ./.github/workflows/build-release.yaml

  publish:
    needs: build-release
    uses: ./.github/workflows/publish.yaml
